# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('city', models.CharField(default='hangzhou', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.User')),
            ],
        ),
    ]
